import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { TrendingUp, AlertTriangle, ArrowLeft, Zap } from 'lucide-react';
import { api } from '../api/client';
import { useAuth } from '../context/AuthContext';

export default function UpgradePage() {
  const navigate    = useNavigate();
  const { user }    = useAuth();
  const [loading, setLoading] = useState(false);

  if (!user) {
    navigate('/login', { replace: true });
    return null;
  }

  async function handleContinue() {
    setLoading(true);
    try {
      const data = await api.createCheckout();
      window.location.href = data.url;
    } catch (e) {
      alert(e.message);
      setLoading(false);
    }
  }

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-primary)', display: 'flex', flexDirection: 'column' }}>
      {/* Nav */}
      <motion.nav
        initial={{ y: -20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} transition={{ duration: 0.4 }}
        style={{
          position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100,
          display: 'flex', alignItems: 'center', padding: '0 2rem', height: '60px',
          background: 'rgba(8,12,16,0.9)', backdropFilter: 'blur(12px)',
          borderBottom: '1px solid var(--border)',
        }}
      >
        <button
          onClick={() => navigate(-1)}
          style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', background: 'none', border: 'none', color: 'var(--text-muted)', fontSize: '0.85rem', cursor: 'pointer' }}
        >
          <ArrowLeft size={14} /> Back
        </button>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.45rem', position: 'absolute', left: '50%', transform: 'translateX(-50%)' }}>
          <div style={{ width: 26, height: 26, borderRadius: 6, background: 'linear-gradient(135deg,#1d9bf0,#0066cc)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
            <TrendingUp size={14} color="#fff" />
          </div>
          <span style={{ fontFamily: 'Space Grotesk, sans-serif', fontWeight: 700, fontSize: '1rem', color: 'var(--text-primary)' }}>
            Strike<span style={{ color: 'var(--accent-blue)' }}>Edge</span>
          </span>
        </div>
      </motion.nav>

      <div style={{ maxWidth: 560, margin: '0 auto', padding: '6rem 1.5rem 4rem', flex: 1 }}>
        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>

          <h1 style={{ fontSize: '1.75rem', fontWeight: 800, letterSpacing: '-0.5px', marginBottom: '0.4rem' }}>
            Upgrade to Premium
          </h1>
          <p style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: '2rem' }}>
            $40 CAD / month · Cancel anytime
          </p>

          {/* Disclaimer box */}
          <div style={{
            borderRadius: 14,
            border: '1px solid rgba(245,158,11,0.3)',
            background: 'rgba(245,158,11,0.06)',
            padding: '1.5rem',
            marginBottom: '1.5rem',
          }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', marginBottom: '1rem' }}>
              <AlertTriangle size={18} color="#f59e0b" />
              <span style={{ fontWeight: 700, fontSize: '0.95rem', color: '#f59e0b' }}>Please read before subscribing</span>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.85rem' }}>
              <DisclaimerItem>
                StrikeEdge is a <strong>data and analytics tool</strong> — not a betting service. All picks are generated by a statistical model and should be used as one input among many, not as guaranteed advice.
              </DisclaimerItem>
              <DisclaimerItem>
                <strong>No model wins every bet.</strong> Past model performance does not guarantee future results. You should apply your own knowledge and judgement before placing any wager.
              </DisclaimerItem>
              <DisclaimerItem>
                <strong>The house always has an edge.</strong> Sports betting is designed to be profitable for the sportsbook over time. Never bet more than you can afford to lose, and treat it as entertainment — not income.
              </DisclaimerItem>
              <DisclaimerItem>
                If gambling is causing you distress, free help is available 24/7 at <strong>1-800-GAMBLER</strong> (US) or visit{' '}
                <a href="https://www.ncpgambling.org" target="_blank" rel="noopener noreferrer" style={{ color: 'var(--accent-blue)' }}>ncpgambling.org</a>.
              </DisclaimerItem>
            </div>
          </div>

          {/* What's included */}
          <div style={{
            borderRadius: 14,
            border: '1px solid var(--border)',
            background: 'var(--bg-card)',
            padding: '1.25rem 1.5rem',
            marginBottom: '2rem',
          }}>
            <p style={{ fontSize: '0.78rem', color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.08em', marginBottom: '0.75rem' }}>What's included</p>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
              {[
                'All daily strikeout prop picks — full slate',
                'All daily hit prop picks — full slate',
                'Performance analytics & win-rate tracking',
                'Full bet history log',
              ].map(item => (
                <div key={item} style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', fontSize: '0.88rem', color: 'var(--text-secondary)' }}>
                  <div style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--accent-blue)', flexShrink: 0 }} />
                  {item}
                </div>
              ))}
            </div>
          </div>

          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={handleContinue}
            disabled={loading}
            style={{
              width: '100%', padding: '0.85rem', borderRadius: 10, border: 'none',
              background: 'linear-gradient(135deg, #1d9bf0, #0066cc)',
              color: '#fff', fontSize: '1rem', fontWeight: 700, cursor: loading ? 'wait' : 'pointer',
              display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.5rem',
            }}
          >
            <Zap size={16} />
            {loading ? 'Redirecting to checkout…' : 'Continue to Checkout'}
          </motion.button>

          <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textAlign: 'center', marginTop: '1rem', lineHeight: 1.6 }}>
            By continuing you confirm you have read and understood the above. You will be redirected to Stripe to complete payment securely.
          </p>
        </motion.div>
      </div>
    </div>
  );
}

function DisclaimerItem({ children }) {
  return (
    <p style={{ fontSize: '0.86rem', color: 'var(--text-secondary)', lineHeight: 1.65, margin: 0 }}>
      {children}
    </p>
  );
}
